gateways:
  local:
    connection:
      type: spark
      config:
        spark.sql.extensions: org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
        spark.sql.catalog.spark_catalog: org.apache.iceberg.spark.SparkSessionCatalog
        spark.sql.catalog.spark_catalog.type: hive
        spark.sql.catalog.local: org.apache.iceberg.spark.SparkCatalog
        spark.sql.catalog.local.type: hadoop
        spark.sql.catalog.local.warehouse: ./warehouse
    
    state_connection:
      type: duckdb
      database: ./warehouse/state.duckdb

default_gateway: local

model_defaults:
  dialect: spark
  start: 2024-11-07
