gateways:
  local:
    connection:
      type: duckdb
      database: /Users/mattiasthalen/Repositories/arcane-insight/data/bronze/bronze.duckdb

default_gateway: local

model_defaults:
  dialect: duckdb
  start: 2024-11-06
