gateways:
  local:
    connection:
      type: duckdb
      database: ./data/arcane_insight.duckdb

default_gateway: local
default_target_environment: dev

model_defaults:
  dialect: duckdb
  start: 2024-11-06

model_naming:
  infer_names: true