MODEL (
  kind INCREMENTAL_BY_UNIQUE_KEY (
    unique_key _sqlmesh_hashkey
  ),
  columns (
    id BIGINT,
    collectible BIGINT,
    slug TEXT,
    class_id BIGINT,
    spell_school_id BIGINT,
    card_type_id BIGINT,
    card_set_id BIGINT,
    rarity_id BIGINT,
    artist_name TEXT,
    mana_cost BIGINT,
    name TEXT,
    text TEXT,
    image TEXT,
    image_gold TEXT,
    flavor_text TEXT,
    crop_image TEXT,
    is_zilliax_functional_module BOOLEAN,
    is_zilliax_cosmetic_module BOOLEAN,
    _dlt_load_id TEXT,
    _dlt_id TEXT,
    health BIGINT,
    attack BIGINT,
    minion_type_id BIGINT,
    rune_cost__blood BIGINT,
    rune_cost__frost BIGINT,
    rune_cost__unholy BIGINT,
    armor BIGINT,
    durability BIGINT,
    parent_id BIGINT,
    banned_from_sideboard BIGINT,
    tourist_class_id BIGINT,
    copy_of_card_id BIGINT,
    max_sideboard_cards BIGINT,
    _dlt_loaded_at TIMESTAMP,
    _sqlmesh_hashkey BLOB,
    _sqlmesh_loaded_at TIMESTAMP
  ),
  grain (
    id
  )
);

SELECT
  id,
  collectible,
  slug,
  class_id,
  spell_school_id,
  card_type_id,
  card_set_id,
  rarity_id,
  artist_name,
  mana_cost,
  name,
  text,
  image,
  image_gold,
  flavor_text,
  crop_image,
  is_zilliax_functional_module,
  is_zilliax_cosmetic_module,
  _dlt_load_id,
  _dlt_id,
  health,
  attack,
  minion_type_id,
  rune_cost__blood,
  rune_cost__frost,
  rune_cost__unholy,
  armor,
  durability,
  parent_id,
  banned_from_sideboard,
  tourist_class_id,
  copy_of_card_id,
  max_sideboard_cards,
  TO_TIMESTAMP(_dlt_load_id::DOUBLE) AS _dlt_loaded_at,
  @generate_surrogate_key(
    id,
    collectible,
    slug,
    class_id,
    spell_school_id,
    card_type_id,
    card_set_id,
    rarity_id,
    artist_name,
    mana_cost,
    name,
    text,
    image,
    image_gold,
    flavor_text,
    crop_image,
    is_zilliax_functional_module,
    is_zilliax_cosmetic_module,
    health,
    attack,
    minion_type_id,
    rune_cost__blood,
    rune_cost__frost,
    rune_cost__unholy,
    armor,
    durability,
    parent_id,
    banned_from_sideboard,
    tourist_class_id,
    copy_of_card_id,
    max_sideboard_cards,
    _dlt_id
  ) AS _sqlmesh_hashkey,
  @execution_ts::TIMESTAMP AS _sqlmesh_loaded_at
FROM bronze.raw_hearthstone_cards /* WHERE */ /*   TO_TIMESTAMP(CAST(_dlt_load_id AS DOUBLE)) BETWEEN @start_ds AND @end_ds */